export const verbosInfinitivo = [{"verb"  :  "To absorb" , "meaning" : "absorver"
},{"verb"  :  "To learn" , "meaning" : "aprender"
},{"verb"  :  "To add" , "meaning" : "Agregar"
},{"verb"  :  "To leave" , "meaning" : "irse, dejar"
},{"verb"  :  "To answer" , "meaning" : "Responder"
},{"verb"  :  "To left" , "meaning" : "dejar"
},{"verb"  :  "To appear" , "meaning" : "Aparecer"
},{"verb"  :  "To list" , "meaning" : "listar"
},{"verb"  :  "To arrive" , "meaning" : "Llegar"
},{"verb"  :  "To listen" , "meaning" : "escuchar"
},{"verb"  :  "To ask" , "meaning" : "Preguntar"
},{"verb"  :  "To live" , "meaning" : "vivir"
},{"verb"  :  "To bark" , "meaning" : "Ladrar"
},{"verb"  :  "To look" , "meaning" : "ver"
},{"verb"  :  "To be" , "meaning" : "Ser, estar"
},{"verb"  :  "To loose" , "meaning" : "perder"
},{"verb"  :  "To became" , "meaning" : "llegar a ser"
},{"verb"  :  "To make" , "meaning" : "hacer, fabricar"
},{"verb"  :  "To belong" , "meaning" : "pertenecer"
},{"verb"  :  "To born" , "meaning" : "nacer"
},{"verb"  :  "To mean" , "meaning" : "significar"
},{"verb"  :  "To build" , "meaning" : "construir"
},{"verb"  :  "To modify" , "meaning" : "modificar"
},{"verb"  :  "To move" , "meaning" : "mover"
},{"verb"  :  "To clarify" , "meaning" : "aclarar"
},{"verb"  :  "To clean" , "meaning" : "limpiar"
},{"verb"  :  "To play" , "meaning" : "jugar,tocar un instrumento,actuar"
},{"verb"  :  "To close" , "meaning" : "cerrar"
},{"verb"  :  "To pull" , "meaning" : "empujar"
},{"verb"  :  "To contain" , "meaning" : "contener"
},{"verb"  :  "To put" , "meaning" : "poner, colocar"
},{"verb"  :  "To cook" , "meaning" : "cocinar"
},{"verb"  :  "To reach" , "meaning" : "alcanzar"
},{"verb"  :  "To cost" , "meaning" : "costar"
},{"verb"  :  "To read" , "meaning" : "leer"
},{"verb"  :  "To cover" , "meaning" : "cubrir"
},{"verb"  :  "To record" , "meaning" : "grabar"
},{"verb"  :  "To crack" , "meaning" : "romper"
},{"verb"  :  "To refuse" , "meaning" : "rechazar"
},{"verb"  :  "To create" , "meaning" : "crear"
},{"verb"  :  "To remain" , "meaning" : "permanecer"
},{"verb"  :  "To cross" , "meaning" : "cruzar"
},{"verb"  :  "To remember" , "meaning" : "recordar"
},{"verb"  :  "To cry" , "meaning" : "llorar"
},{"verb"  :  "To repair" , "meaning" : "reparar"
},{"verb"  :  "To dark" , "meaning" : "oscurecer"
},{"verb"  :  "To return" , "meaning" : "regresar"
},{"verb"  :  "To die" , "meaning" : "morir"
},{"verb"  :  "To save" , "meaning" : "Salvar, ahorrar"
},{"verb"  :  "To discover" , "meaning" : "descubrir"
},{"verb"  :  "To schedule" , "meaning" : "Programar, planear"
},{"verb"  :  "To draw" , "meaning" : "dibujar"
},{"verb"  :  "To sell" , "meaning" : "vender"
},{"verb"  :  "To drink" , "meaning" : "beber"
},{"verb"  :  "To set" , "meaning" : "poner, colocar"
},{"verb"  :  "To drive" , "meaning" : "manejar"
},{"verb"  :  "To shine" , "meaning" : "amanecer"
},{"verb"  :  "To dry" , "meaning" : "secar"
},{"verb"  :  "To show" , "meaning" : "mostrar"
},{"verb"  :  "To ear" , "meaning" : "oír"
},{"verb"  :  "To sing" , "meaning" : "cantar"
},{"verb"  :  "To eat" , "meaning" : "comer"
},{"verb"  :  "To sit" , "meaning" : "sentar"
},{"verb"  :  "To elect" , "meaning" : "elegir"
},{"verb"  :  "To sleep" , "meaning" : "dormir"
},{"verb"  :  "To entertain" , "meaning" : "entretener"
},{"verb"  :  "To smell" , "meaning" : "oler"
},{"verb"  :  "To exchange" , "meaning" : "intercambiar"
},{"verb"  :  "To Smile" , "meaning" : "Sonreir"
},{"verb"  :  "To experiment" , "meaning" : "experimentar"
},{"verb"  :  "To solve" , "meaning" : "resolver"
},{"verb"  :  "To explain" , "meaning" : "explicar"
},{"verb"  :  "To sound" , "meaning" : "sonar"
},{"verb"  :  "To express" , "meaning" : "expresar"
},{"verb"  :  "To speak" , "meaning" : "hablar"
},{"verb"  :  "To feel" , "meaning" : "sentir"
},{"verb"  :  "To stay" , "meaning" : "estar, permanecer"
},{"verb"  :  "To finish" , "meaning" : "terminar"
},{"verb"  :  "To stop" , "meaning" : "detener"
},{"verb"  :  "To fix" , "meaning" : "arreglar"
},{"verb"  :  "To study" , "meaning" : "estudiar"
},{"verb"  :  "To fly" , "meaning" : "volar"
},{"verb"  :  "To swim" , "meaning" : "nadar"
},{"verb"  :  "To follow" , "meaning" : "seguir"
},{"verb"  :  "To take","meaning"  :  "Tomar"
},{"verb"  :  "To formulate" , "meaning" : "formular"
},{"verb"  :  "To taste" , "meaning" : "probar"
},{"verb"  :  "To found" , "meaning" : "encontrar"
},{"verb"  :  "To tell" , "meaning" : "decir, hablar"
},{"verb"  :  "To freeze" , "meaning" : "congelar"
},{"verb"  :  "To translate" , "meaning" : "traducir"
},{"verb"  :  "To fun" , "meaning" : "divertir"
},{"verb"  :  "To travel" , "meaning" : "viajar"
},{"verb"  :  "To gift" , "meaning" : "regalar"
},{"verb"  :  "To try" , "meaning" : "intentar"
},{"verb"  :  "To give" , "meaning" : "dar"
},{"verb"  :  "To turn on" , "meaning" : "encender"
},{"verb"  :  "To go" , "meaning" : "ir"
},{"verb"  :  "To type" , "meaning" : "Escribir a máquina,teclear"
},{"verb"  :  "To grow" , "meaning" : "crecer"
},{"verb"  :  "To underline" , "meaning" : "subrayar"
},{"verb"  :  "To have" , "meaning" : "tener"
},{"verb"  :  "To use" , "meaning" : "usar"
},{"verb"  :  "To help" , "meaning" : "ayudar"
},{"verb"  :  "To wake" , "meaning" : "despertar"
},{"verb"  :  "To honor" , "meaning" : "honrar"
},{"verb"  :  "To walk" , "meaning" : "caminar"
},{"verb"  :  "To include" , "meaning" : "incluir"
},{"verb"  :  "To wash" , "meaning" : "lavar"
},{"verb"  :  "To insist" , "meaning" : "insistir"
},{"verb"  :  "To wear" , "meaning" : "usar"
},{"verb"  :  "To interrupt" , "meaning" : "interrumpir"
},{"verb"  :  "To work" , "meaning" : "trabajar"
},{"verb"  :  "To jump" , "meaning" : "saltar"
},{"verb"  :  "To write" , "meaning" : "Escribir"
},{"verb"  :  "To know" , "meaning" : "saber"
},{"verb"  :  "To zoom" , "meaning" : "moverse con rapidez"}]
